// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.14.0
// source: car.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Car struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsManual     bool    `protobuf:"varint,2,opt,name=is_manual,json=isManual,proto3" json:"is_manual,omitempty"`
	Manufacturer string  `protobuf:"bytes,3,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Model        string  `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	SampleLists  []int32 `protobuf:"varint,5,rep,packed,name=sample_lists,json=sampleLists,proto3" json:"sample_lists,omitempty"`
}

func (x *Car) Reset() {
	*x = Car{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Car) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Car) ProtoMessage() {}

func (x *Car) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Car.ProtoReflect.Descriptor instead.
func (*Car) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{0}
}

func (x *Car) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Car) GetIsManual() bool {
	if x != nil {
		return x.IsManual
	}
	return false
}

func (x *Car) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *Car) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Car) GetSampleLists() []int32 {
	if x != nil {
		return x.SampleLists
	}
	return nil
}

type Vehicles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Vehicles) Reset() {
	*x = Vehicles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vehicles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicles) ProtoMessage() {}

func (x *Vehicles) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicles.ProtoReflect.Descriptor instead.
func (*Vehicles) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{1}
}

type Dealership struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address   string          `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Inventory []*Car          `protobuf:"bytes,3,rep,name=inventory,proto3" json:"inventory,omitempty"`
	Sedans    *Vehicles_Sedan `protobuf:"bytes,4,opt,name=sedans,proto3" json:"sedans,omitempty"`
}

func (x *Dealership) Reset() {
	*x = Dealership{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dealership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dealership) ProtoMessage() {}

func (x *Dealership) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dealership.ProtoReflect.Descriptor instead.
func (*Dealership) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{2}
}

func (x *Dealership) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dealership) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Dealership) GetInventory() []*Car {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *Dealership) GetSedans() *Vehicles_Sedan {
	if x != nil {
		return x.Sedans
	}
	return nil
}

type Vehicles_Sedan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accord []*Car `protobuf:"bytes,1,rep,name=accord,proto3" json:"accord,omitempty"`
	Civic  []*Car `protobuf:"bytes,2,rep,name=civic,proto3" json:"civic,omitempty"`
}

func (x *Vehicles_Sedan) Reset() {
	*x = Vehicles_Sedan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vehicles_Sedan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicles_Sedan) ProtoMessage() {}

func (x *Vehicles_Sedan) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicles_Sedan.ProtoReflect.Descriptor instead.
func (*Vehicles_Sedan) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Vehicles_Sedan) GetAccord() []*Car {
	if x != nil {
		return x.Accord
	}
	return nil
}

func (x *Vehicles_Sedan) GetCivic() []*Car {
	if x != nil {
		return x.Civic
	}
	return nil
}

type Vehicles_Suv struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accord []*Car `protobuf:"bytes,1,rep,name=accord,proto3" json:"accord,omitempty"`
	Civic  []*Car `protobuf:"bytes,2,rep,name=civic,proto3" json:"civic,omitempty"`
}

func (x *Vehicles_Suv) Reset() {
	*x = Vehicles_Suv{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vehicles_Suv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicles_Suv) ProtoMessage() {}

func (x *Vehicles_Suv) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicles_Suv.ProtoReflect.Descriptor instead.
func (*Vehicles_Suv) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Vehicles_Suv) GetAccord() []*Car {
	if x != nil {
		return x.Accord
	}
	return nil
}

func (x *Vehicles_Suv) GetCivic() []*Car {
	if x != nil {
		return x.Civic
	}
	return nil
}

var File_car_proto protoreflect.FileDescriptor

var file_car_proto_rawDesc = []byte{
	0x0a, 0x09, 0x63, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x69, 0x6e, 0x76,
	0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x8f, 0x01, 0x0a, 0x03, 0x43, 0x61, 0x72, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x69, 0x73, 0x5f, 0x6d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x69, 0x73, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x6d,
	0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x22, 0xb6, 0x01, 0x0a, 0x08, 0x56, 0x65, 0x68,
	0x69, 0x63, 0x6c, 0x65, 0x73, 0x1a, 0x55, 0x0a, 0x05, 0x53, 0x65, 0x64, 0x61, 0x6e, 0x12, 0x26,
	0x0a, 0x06, 0x61, 0x63, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x43, 0x61, 0x72, 0x52, 0x06,
	0x61, 0x63, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x24, 0x0a, 0x05, 0x63, 0x69, 0x76, 0x69, 0x63, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72,
	0x79, 0x2e, 0x43, 0x61, 0x72, 0x52, 0x05, 0x63, 0x69, 0x76, 0x69, 0x63, 0x1a, 0x53, 0x0a, 0x03,
	0x53, 0x75, 0x76, 0x12, 0x26, 0x0a, 0x06, 0x61, 0x63, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e,
	0x43, 0x61, 0x72, 0x52, 0x06, 0x61, 0x63, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x24, 0x0a, 0x05, 0x63,
	0x69, 0x76, 0x69, 0x63, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x69, 0x6e, 0x76,
	0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x43, 0x61, 0x72, 0x52, 0x05, 0x63, 0x69, 0x76, 0x69,
	0x63, 0x22, 0x9b, 0x01, 0x0a, 0x0a, 0x44, 0x65, 0x61, 0x6c, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2c,
	0x0a, 0x09, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x43, 0x61,
	0x72, 0x52, 0x09, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x31, 0x0a, 0x06,
	0x73, 0x65, 0x64, 0x61, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69,
	0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65,
	0x73, 0x2e, 0x53, 0x65, 0x64, 0x61, 0x6e, 0x52, 0x06, 0x73, 0x65, 0x64, 0x61, 0x6e, 0x73, 0x42,
	0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68,
	0x61, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x64, 0x65, 0x61, 0x6c, 0x65, 0x72, 0x73, 0x68, 0x69,
	0x70, 0x2d, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_car_proto_rawDescOnce sync.Once
	file_car_proto_rawDescData = file_car_proto_rawDesc
)

func file_car_proto_rawDescGZIP() []byte {
	file_car_proto_rawDescOnce.Do(func() {
		file_car_proto_rawDescData = protoimpl.X.CompressGZIP(file_car_proto_rawDescData)
	})
	return file_car_proto_rawDescData
}

var file_car_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_car_proto_goTypes = []interface{}{
	(*Car)(nil),            // 0: inventory.Car
	(*Vehicles)(nil),       // 1: inventory.Vehicles
	(*Dealership)(nil),     // 2: inventory.Dealership
	(*Vehicles_Sedan)(nil), // 3: inventory.Vehicles.Sedan
	(*Vehicles_Suv)(nil),   // 4: inventory.Vehicles.Suv
}
var file_car_proto_depIdxs = []int32{
	0, // 0: inventory.Dealership.inventory:type_name -> inventory.Car
	3, // 1: inventory.Dealership.sedans:type_name -> inventory.Vehicles.Sedan
	0, // 2: inventory.Vehicles.Sedan.accord:type_name -> inventory.Car
	0, // 3: inventory.Vehicles.Sedan.civic:type_name -> inventory.Car
	0, // 4: inventory.Vehicles.Suv.accord:type_name -> inventory.Car
	0, // 5: inventory.Vehicles.Suv.civic:type_name -> inventory.Car
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_car_proto_init() }
func file_car_proto_init() {
	if File_car_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_car_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Car); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vehicles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dealership); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vehicles_Sedan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vehicles_Suv); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_car_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_car_proto_goTypes,
		DependencyIndexes: file_car_proto_depIdxs,
		MessageInfos:      file_car_proto_msgTypes,
	}.Build()
	File_car_proto = out.File
	file_car_proto_rawDesc = nil
	file_car_proto_goTypes = nil
	file_car_proto_depIdxs = nil
}
